version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      - mysql
      - rabbitmq
      - elasticsearch
    volumes:
      - ./src:/var/www/html/
    networks:
      - app-network
    ports:
      - "80:80"
      - "6001:6001"

  elasticsearch:
    container_name: elasticsearch_container
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
    networks:
      - app-network

  solr:
    container_name: solr_container
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./solr:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    networks:
      - app-network

  kibana:
    container_name: kibana_container
    image: kibana:8.6.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch_container:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch_container:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

  mysql:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appdb
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.9.28-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  nsqlookupd:
    container_name: nsqlookupd_container
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - app-network

  nsqd:
    container_name: nsqd_container
    image: nsqio/nsq
    command: /nsqd --broadcast-address nsqd --lookupd-tcp-address=nsqlookupd:4160
    links:
      - nsqlookupd:nsqlookupd
    depends_on:
      - nsqlookupd
    ports:
      - "64150:4150"
      - "64151:4150"
    networks:
      - app-network

  nsqadmin:
    container_name: nsqadmin_container
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    links:
      - nsqlookupd:nsqlookupd
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
